# Generated by Django 5.1.6 on 2025-02-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studadm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
                ('std', models.CharField(max_length=5)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
