# Generated by Django 5.1.6 on 2025-02-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studadm',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='studadm',
            old_name='lastname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='studadm',
            old_name='std',
            new_name='standard',
        ),
        migrations.RemoveField(
            model_name='studadm',
            name='age',
        ),
        migrations.AddField(
            model_name='studadm',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
